# numpy

In [3]:
import numpy as np

In [5]:
my_list=[1,4,2,50]
arr=np.array(my_list)
arr

array([ 1,  4,  2, 50])

In [7]:
print(arr.shape)

(4,)


In [4]:
l1=[1,2,3,4]
l2=[2,4,6,8]
l3=[3,6,9,12]
arr=np.array([l1,l2,l3])

In [5]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  2,  4],
       [ 6,  8,  3],
       [ 6,  9, 12]])

In [7]:
arr

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [6]:
arr[0:][2:]

array([[ 3,  6,  9, 12]])

In [23]:
arr

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [33]:
arr[1:,:1]

array([[2],
       [3]])

In [35]:
arr2=np.arange(0,10,2)
arr2

array([0, 2, 4, 6, 8])

In [40]:
np.linspace(2,5,7)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [43]:
#COPy fun

arr[1]=100
arr

array([[  1,   2,   3,   4],
       [100, 100, 100, 100],
       [  3,   6,   9,  12]])

In [46]:
arr1=arr
arr1[2]=500
arr

array([[  1,   2,   3,   4],
       [100, 100, 100, 100],
       [500, 500, 500, 500]])

In [50]:
arr1=arr.copy()
arr1[1]=200
arr

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [57]:
#USeful



arr[arr<6]

array([1, 2, 3, 4, 2, 4, 3])

In [62]:
on=np.ones((3,4),dtype=int)
on

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [69]:
np.random.rand(4,4)

array([[0.19938232, 0.68549036, 0.71098619, 0.99390974],
       [0.55653296, 0.83245613, 0.29771125, 0.44128904],
       [0.91799764, 0.18603764, 0.68242345, 0.84935952],
       [0.8478027 , 0.90464302, 0.88475423, 0.01200275]])

In [21]:
np.random.randint(1,3,1)

array([1])