# Numpy

In [ ]:
g_s='restart'
mod=set()
''.join(i) for i in s if  not in mod

In [35]:
g_s='restart';
res=g_s
mod=set()

for i in range(len(g_s)):
    if g_s[i] in mod:
        print(g_s[i])
        res=res.replace(g_s[i],"$")
        print(res)
    else:
        mod.add(g_s[i])


r
$esta$t
t
$es$a$$


In [34]:
a='1234'
print(a.replace("a","$"))


1234


In [37]:
s="lres"
'yes' if s[0]=='r' else 'NO'

'NO'

In [12]:
s="Last Checkpoint: Last Saturday at "
s[::-1]
s[0:6:2]
res=''
for i in s.split(' '):
    print(i)
    res+=i[::-1]+' '
print(res)

Last
Checkpoint:
Last
Saturday
at

tsaL :tniopkcehC tsaL yadrutaS ta  


In [31]:
import string
print(len(set(string.ascii_lowercase)))
inp='The quick brown f jumps over the lay dog'
if len(set(inp)) >=26:
    print(True)
else:
    print(False)

26
True


In [18]:
input='the quickbrownfoxjumpsoverthelazydog'
a=dict()
for i in input:
    if i in a:
        a[i]+=1
    else:
        a[i]=1
for x in a:
    if a[x]>1:
        print(x,a[x])
        
for z in input:
    if input.count(z)>1:
        print(z,input.count(z))

t 2
h 2
e 3
u 2
r 2
o 4
t 2
h 2
e 3
u 2
r 2
o 4
o 4
u 2
o 4
e 3
r 2
t 2
h 2
e 3
o 4


In [19]:
count=0
for i in input:
    print('Current character {} position at {}'.format(i,count))
    count+=1

Current character t position at 0
Current character h position at 1
Current character e position at 2
Current character   position at 3
Current character q position at 4
Current character u position at 5
Current character i position at 6
Current character c position at 7
Current character k position at 8
Current character b position at 9
Current character r position at 10
Current character o position at 11
Current character w position at 12
Current character n position at 13
Current character f position at 14
Current character o position at 15
Current character x position at 16
Current character j position at 17
Current character u position at 18
Current character m position at 19
Current character p position at 20
Current character s position at 21
Current character o position at 22
Current character v position at 23
Current character e position at 24
Current character r position at 25
Current character t position at 26
Current character h position at 27
Current character e position a

In [27]:
if len(set(input))>=26:
    print('yes {}'.format(len(set(input))))
else:
    print('no')

yes 27


In [30]:
input

'the quickbrownfoxjumpsoverthelazydog'

In [ ]:
for i in range(5):
    input.format(str)

In [31]:
instr="32.054,23"
instr=instr.replace('.','*')
instr=instr.replace(',','.')
instr=instr.replace('*',',')
print(instr)

32,054.23


In [37]:
count=0
res=dict()
vowels=['a','e','i','o','u']
for i in set(input):
    if i in vowels:
        print('character {} in {} places '.format(i,input.count(i)))
        
        

character e in 3 places 
character u in 2 places 
character a in 1 places 
character i in 1 places 
character o in 4 places 


In [42]:
a=input.split('e')
for i in a:
    print(i+'e')

the
 quickbrownfoxjumpsove
rthe
lazydoge


In [51]:
srt='Python Exercises Practice Solution Exercises'
for i in set(srt.split(' ')):
    print(i,end=' ')

Practice Exercises Solution Python 

In [52]:
print('t')

t


In [64]:
import numpy as np
a=[1,3,4,5,5,6,7,8,9,10,1,1]
#a = np.arange(9)
a=np.array(a)
aree=np.split(a,2)
print(aree)

[array([1, 3, 4, 5, 5, 6]), array([ 7,  8,  9, 10,  1,  1])]


In [56]:
print(np.arange(8))

[0 1 2 3 4 5 6 7]


In [70]:
a = np.arange(8)
split_arr = np.split(a, 2)
for i in split_arr:
    print((i))

[0 1 2 3]
[4 5 6 7]


In [69]:
np.fliplr(split_arr)

array([[3, 2, 1, 0],
       [7, 6, 5, 4]])

In [71]:
np.flipud(split_arr)

array([[4, 5, 6, 7],
       [0, 1, 2, 3]])

In [74]:
arr = np.array(['i', 'love', 'NumPy', 'AND', 'interviewbit'], dtype=str)
np.char.upper(arr)
np.char.swapcase(arr)

array(['I', 'LOVE', 'nUMpY', 'and', 'INTERVIEWBIT'], dtype='<U12')

In [75]:
arr = np.array(['22', '9', '1234', '567', '89102'], dtype=str)
np.char.zfill(arr,8)

array(['00000022', '00000009', '00001234', '00000567', '00089102'],
      dtype='<U8')

In [77]:
a=['1','2','3','4','5']
a=np.array(a)
np.char.zfill(a,8)

array(['00000001', '00000002', '00000003', '00000004', '00000005'],
      dtype='<U8')

In [78]:
arr

array(['22', '9', '1234', '567', '89102'], dtype='<U5')

In [82]:
arr = np.array(['i', 'love', 'NumPy', 'AND', 'interviewbit'], dtype=str)


np.char.join(' ',arr)

array(['i', 'l o v e', 'N u m P y', 'A N D', 'i n t e r v i e w b i t'],
      dtype='<U23')

In [83]:
np.char.multiply(arr,5)

array(['iiiii', 'lovelovelovelovelove', 'NumPyNumPyNumPyNumPyNumPy',
       'ANDANDANDANDAND',
       'interviewbitinterviewbitinterviewbitinterviewbitinterviewbit'],
      dtype='<U60')

In [84]:
res=np.arange(10,60)
res

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [88]:
one=np.ones((3,3))
np.pad(one,pad_width=1)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [89]:
in_arr=np.arange(10)
np.shape(in_arr)

(10,)

In [91]:
print(in_arr)
np.reshape(in_arr,(2,5))

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [96]:
in_arr
np.swapaxes(in_arr,0,1)

AxisError: axis2: axis 1 is out of bounds for array of dimension 1

#NUMPy

In [104]:
a=[1,2,3]
b=[2,3,4]



In [98]:
import numpy as np
print(np.cross(a,b))

[-1  2 -1]


In [100]:
a[0]*3

3

In [103]:
import numpy as np
from numpy import linalg as la
a=np.array([[1,3],[2,4]])

print(np.linalg.det(a))

-2.0


In [105]:
np.multiply(a,b)

array([ 2,  6, 12])

In [106]:
np.cross(a,b)

array([-1,  2, -1])

In [109]:
a = np.array([[1, 0], [1, 2]])
np.linalg.det(a)

2.0

In [ ]:
np.einsum()